### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by Alvant** [khomi-a/homework#1]
@khomi-a это типа тестовый репозиторий?) а основной — advanced_python?

Кстати, скажите, пожалуйста, как вас зовут (лучше письмо на почту отправить, чтоб я точно увидел)?
А то у меня по вашему имени профиля "identification failed" получается :sweat_smile:

**Comment by Alvant** [comment]
... :thinking: ... Андрей Хомутов?)

**Comment by khomi-a** [comment]
Я там несколько их создал и смогу только вечером отписать (когда/если
разберусь)).

С уважением, староста 903ей группы Хомутов Андрей

пт, 10 сент. 2021 г., 12:48 Vasiliy ***@***.***>:
